// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDriOuAhrTz1ErPXHO-HhgUNXvW-O77XUc',
    appId: '1:1011843952929:web:8037e29ffaf1f23bface60',
    messagingSenderId: '1011843952929',
    projectId: 'clinigo-2026',
    authDomain: 'clinigo-2026.firebaseapp.com',
    storageBucket: 'clinigo-2026.firebasestorage.app',
    measurementId: 'G-L5ZN2F4V1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8QrAYGkDZOxnHj67rp6_5VbYmhd7km2w',
    appId: '1:1011843952929:android:3ccb6ac51922d025face60',
    messagingSenderId: '1011843952929',
    projectId: 'clinigo-2026',
    storageBucket: 'clinigo-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKtpQbDH4xtses26WxFAadwRWDBmAFxec',
    appId: '1:1011843952929:ios:e029c7b359812313face60',
    messagingSenderId: '1011843952929',
    projectId: 'clinigo-2026',
    storageBucket: 'clinigo-2026.firebasestorage.app',
    androidClientId: '1011843952929-qlnas1pgr8tju4f4t9adg9k9ku0bhf61.apps.googleusercontent.com',
    iosClientId: '1011843952929-lj3o2s6pob0ib5okbl11rrt74ijvf8bf.apps.googleusercontent.com',
    iosBundleId: 'com.supertechlb.clinigo',
  );
}
